CREATE DATABASE IF NOT EXISTS morris_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE morris_db;
CREATE TABLE IF NOT EXISTS players (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  stars INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS rooms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(8) NOT NULL UNIQUE,
  status ENUM('waiting','playing','finished') NOT NULL DEFAULT 'waiting',
  p1_id INT NULL,
  p2_id INT NULL,
  winner_id INT NULL,
  state_json TEXT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
